version: "3.7"
services:
  httpd-server:
    image: tomsik68/xampp:7.3.7
    container_name: httpd-server
    hostname: httpd-server
    restart: on-failure
    ports:
      - "80:80"
    networks:
      - apache-net
    volumes:
      - ./:/www/
networks:
  apache-net:
    driver: bridge